#!/bin/bash
export DIR=/home/stack/tripleo_hardening_templates

openstack overcloud deploy --templates \
-t 90 --ntp-server 10.5.26.10 \
--libvirt-type qemu \
--control-scale 3 --compute-scale 2 \
--ceph-storage-scale=3 \
-e $DIR/hostname.yaml \
-e $DIR/puppet-pacemaker.yaml \
-e $DIR/network-environment.yaml \
-e $DIR/rhel-registration/environment-rhel-registration.yaml \
-e $DIR/rhel-registration/rhel-registration-resource-registry.yaml \
-e $DIR/enable-tls.yaml \
-e $DIR/inject-trust-anchor.yaml \
-e $DIR/storage-environment.yaml
#--control-flavor control --compute-flavor compute \
#-e $DIR/post-deploy.yaml
