#!/bin/bash
export DIR=/home/stack/templates

openstack overcloud deploy --templates \
-t 90 --ntp-server 10.5.26.10 \
--libvirt-type qemu \
--control-flavor control --compute-flavor compute \
--control-scale 3 --compute-scale 2 \
-e $DIR/storage-environment.yaml \
-e $DIR/network-environment.yaml \
-e $DIR/enable-tls.yaml \
-e $DIR/inject-trust-anchor.yaml \
-e $DIR/hostname.yaml \
-e $DIR/rhel-registration/environment-rhel-registration.yaml \
-e $DIR/rhel-registration/rhel-registration-resource-registry.yaml \
-e $DIR/post-deploy.yaml
