parameters:
  CinderEnableIscsiBackend: false
  CinderEnableRbdBackend: true
  CinderEnableNfsBackend: true
  NovaEnableRbdBackend: false
  GlanceBackend: file
  CinderNfsMountOptions: 'retry=1'
  CinderNfsServers: 172.16.0.254:/nfs/cinder
  GlanceFilePcmkManage: true
  GlanceFilePcmkFstype: nfs
  GlanceFilePcmkDevice: 172.16.0.254:/nfs/glance
  GlanceFilePcmkOptions: 'context=system_u:object_r:glance_var_lib_t:s0'
  ControllerExtraConfig:  
    cinder::api::default_volume_type: 'tripleo_ceph'
